from pydantic import BaseModel
from typing import Optional

class CreateSanction(BaseModel):
    mobile: str
    firstName: str
    lastName: str
    fatherName: str
    gender: str
    idProofTypeFromPartner: str
    idProofNumberFromPartner: str
    addressProofTypeFromPartner: str
    addressProofNumberFromPartner: str
    dob: str
    ownedVehicle: str
    currDoorAndBuilding: str
    currStreetAndLocality: str
    currLandmark: str
    currCity: str
    currDistrict: str
    currState: str
    currPincode: str
    permDoorAndBuilding: str
    permLandmark: str
    permCity: str
    permDistrict: str
    permState: str
    permPincode: str
    occupation: str
    companyName: str
    grossMonthlyIncome: int
    netMonthlyIncome: int
    incomeValidationStatus: str
    pan: str
    purposeOfLoan: str
    loanAmount: int
    interestRate: int
    scheduleStartDate: str
    firstInstallmentDate: str
    totalProcessingFees: int
    gst: int
    preEmiAmount: int
    emi: int
    emiDate: str
    emiWeek: int
    repaymentFrequency: str
    repaymentMode: str
    tenureValue: int
    tenureUnits: str
    productName: str
    primaryBankAccount: str
    bankName: str
    modeOfSalary: str
    clientId: str
    dedupeReferenceId: int
    email: str
    middleName: str
    maritalStatus: str
    loanId: str
